name = "yworkouty"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages用設定
pages_build_output_dir = ".open-next"

# OpenNext output directory
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }
